/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package aspectualacme.provider;

import aspectualacme.util.AspectualacmeAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AspectualacmeItemProviderAdapterFactory extends AspectualacmeAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AspectualacmeItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RootItemProvider rootItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRootAdapter() {
		if (rootItemProvider == null) {
			rootItemProvider = new RootItemProvider(this);
		}

		return rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Element} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElementItemProvider elementItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Element}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElementAdapter() {
		if (elementItemProvider == null) {
			elementItemProvider = new ElementItemProvider(this);
		}

		return elementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniExpressionItemProvider armaniExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniExpressionAdapter() {
		if (armaniExpressionItemProvider == null) {
			armaniExpressionItemProvider = new ArmaniExpressionItemProvider(this);
		}

		return armaniExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniFunctionCall} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniFunctionCallItemProvider armaniFunctionCallItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniFunctionCall}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniFunctionCallAdapter() {
		if (armaniFunctionCallItemProvider == null) {
			armaniFunctionCallItemProvider = new ArmaniFunctionCallItemProvider(this);
		}

		return armaniFunctionCallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniSetExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniSetExpressionItemProvider armaniSetExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniSetExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniSetExpressionAdapter() {
		if (armaniSetExpressionItemProvider == null) {
			armaniSetExpressionItemProvider = new ArmaniSetExpressionItemProvider(this);
		}

		return armaniSetExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniConstant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniConstantItemProvider armaniConstantItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniConstant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniConstantAdapter() {
		if (armaniConstantItemProvider == null) {
			armaniConstantItemProvider = new ArmaniConstantItemProvider(this);
		}

		return armaniConstantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniPrimitiveExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniPrimitiveExpressionItemProvider armaniPrimitiveExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniPrimitiveExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniPrimitiveExpressionAdapter() {
		if (armaniPrimitiveExpressionItemProvider == null) {
			armaniPrimitiveExpressionItemProvider = new ArmaniPrimitiveExpressionItemProvider(this);
		}

		return armaniPrimitiveExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniUnaryExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniUnaryExpressionItemProvider armaniUnaryExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniUnaryExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniUnaryExpressionAdapter() {
		if (armaniUnaryExpressionItemProvider == null) {
			armaniUnaryExpressionItemProvider = new ArmaniUnaryExpressionItemProvider(this);
		}

		return armaniUnaryExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniMultiplicativeExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniMultiplicativeExpressionItemProvider armaniMultiplicativeExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniMultiplicativeExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniMultiplicativeExpressionAdapter() {
		if (armaniMultiplicativeExpressionItemProvider == null) {
			armaniMultiplicativeExpressionItemProvider = new ArmaniMultiplicativeExpressionItemProvider(this);
		}

		return armaniMultiplicativeExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniAdditiveExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniAdditiveExpressionItemProvider armaniAdditiveExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniAdditiveExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniAdditiveExpressionAdapter() {
		if (armaniAdditiveExpressionItemProvider == null) {
			armaniAdditiveExpressionItemProvider = new ArmaniAdditiveExpressionItemProvider(this);
		}

		return armaniAdditiveExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniRelationalExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniRelationalExpressionItemProvider armaniRelationalExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniRelationalExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniRelationalExpressionAdapter() {
		if (armaniRelationalExpressionItemProvider == null) {
			armaniRelationalExpressionItemProvider = new ArmaniRelationalExpressionItemProvider(this);
		}

		return armaniRelationalExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniEqualityExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniEqualityExpressionItemProvider armaniEqualityExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniEqualityExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniEqualityExpressionAdapter() {
		if (armaniEqualityExpressionItemProvider == null) {
			armaniEqualityExpressionItemProvider = new ArmaniEqualityExpressionItemProvider(this);
		}

		return armaniEqualityExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniIffExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniIffExpressionItemProvider armaniIffExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniIffExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniIffExpressionAdapter() {
		if (armaniIffExpressionItemProvider == null) {
			armaniIffExpressionItemProvider = new ArmaniIffExpressionItemProvider(this);
		}

		return armaniIffExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniImpliesExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniImpliesExpressionItemProvider armaniImpliesExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniImpliesExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniImpliesExpressionAdapter() {
		if (armaniImpliesExpressionItemProvider == null) {
			armaniImpliesExpressionItemProvider = new ArmaniImpliesExpressionItemProvider(this);
		}

		return armaniImpliesExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniOrExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniOrExpressionItemProvider armaniOrExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniOrExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniOrExpressionAdapter() {
		if (armaniOrExpressionItemProvider == null) {
			armaniOrExpressionItemProvider = new ArmaniOrExpressionItemProvider(this);
		}

		return armaniOrExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniVariableItemProvider armaniVariableItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniVariableAdapter() {
		if (armaniVariableItemProvider == null) {
			armaniVariableItemProvider = new ArmaniVariableItemProvider(this);
		}

		return armaniVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniBooleanExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniBooleanExpressionItemProvider armaniBooleanExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniBooleanExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniBooleanExpressionAdapter() {
		if (armaniBooleanExpressionItemProvider == null) {
			armaniBooleanExpressionItemProvider = new ArmaniBooleanExpressionItemProvider(this);
		}

		return armaniBooleanExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ArmaniQuantifiedExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniQuantifiedExpressionItemProvider armaniQuantifiedExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ArmaniQuantifiedExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniQuantifiedExpressionAdapter() {
		if (armaniQuantifiedExpressionItemProvider == null) {
			armaniQuantifiedExpressionItemProvider = new ArmaniQuantifiedExpressionItemProvider(this);
		}

		return armaniQuantifiedExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Family} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FamilyItemProvider familyItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Family}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFamilyAdapter() {
		if (familyItemProvider == null) {
			familyItemProvider = new FamilyItemProvider(this);
		}

		return familyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ComponentType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentTypeItemProvider componentTypeItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ComponentType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentTypeAdapter() {
		if (componentTypeItemProvider == null) {
			componentTypeItemProvider = new ComponentTypeItemProvider(this);
		}

		return componentTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.RoleType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleTypeItemProvider roleTypeItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.RoleType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleTypeAdapter() {
		if (roleTypeItemProvider == null) {
			roleTypeItemProvider = new RoleTypeItemProvider(this);
		}

		return roleTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.PortType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortTypeItemProvider portTypeItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.PortType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortTypeAdapter() {
		if (portTypeItemProvider == null) {
			portTypeItemProvider = new PortTypeItemProvider(this);
		}

		return portTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.ConnectorType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectorTypeItemProvider connectorTypeItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.ConnectorType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectorTypeAdapter() {
		if (connectorTypeItemProvider == null) {
			connectorTypeItemProvider = new ConnectorTypeItemProvider(this);
		}

		return connectorTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.PropertyType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyTypeItemProvider propertyTypeItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.PropertyType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyTypeAdapter() {
		if (propertyTypeItemProvider == null) {
			propertyTypeItemProvider = new PropertyTypeItemProvider(this);
		}

		return propertyTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.System} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemItemProvider systemItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.System}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemAdapter() {
		if (systemItemProvider == null) {
			systemItemProvider = new SystemItemProvider(this);
		}

		return systemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Component} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentItemProvider componentItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Component}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentAdapter() {
		if (componentItemProvider == null) {
			componentItemProvider = new ComponentItemProvider(this);
		}

		return componentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Connector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectorItemProvider connectorItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Connector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectorAdapter() {
		if (connectorItemProvider == null) {
			connectorItemProvider = new ConnectorItemProvider(this);
		}

		return connectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Role} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleItemProvider roleItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Role}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleAdapter() {
		if (roleItemProvider == null) {
			roleItemProvider = new RoleItemProvider(this);
		}

		return roleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.BaseRole} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BaseRoleItemProvider baseRoleItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.BaseRole}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBaseRoleAdapter() {
		if (baseRoleItemProvider == null) {
			baseRoleItemProvider = new BaseRoleItemProvider(this);
		}

		return baseRoleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.CrosscuttingRole} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CrosscuttingRoleItemProvider crosscuttingRoleItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.CrosscuttingRole}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCrosscuttingRoleAdapter() {
		if (crosscuttingRoleItemProvider == null) {
			crosscuttingRoleItemProvider = new CrosscuttingRoleItemProvider(this);
		}

		return crosscuttingRoleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Port} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortItemProvider portItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortAdapter() {
		if (portItemProvider == null) {
			portItemProvider = new PortItemProvider(this);
		}

		return portItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Property} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyItemProvider propertyItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAdapter() {
		if (propertyItemProvider == null) {
			propertyItemProvider = new PropertyItemProvider(this);
		}

		return propertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Glue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlueItemProvider glueItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Glue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlueAdapter() {
		if (glueItemProvider == null) {
			glueItemProvider = new GlueItemProvider(this);
		}

		return glueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Attachment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttachmentItemProvider attachmentItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Attachment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttachmentAdapter() {
		if (attachmentItemProvider == null) {
			attachmentItemProvider = new AttachmentItemProvider(this);
		}

		return attachmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Binding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindingItemProvider bindingItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Binding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindingAdapter() {
		if (bindingItemProvider == null) {
			bindingItemProvider = new BindingItemProvider(this);
		}

		return bindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Representation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepresentationItemProvider representationItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Representation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepresentationAdapter() {
		if (representationItemProvider == null) {
			representationItemProvider = new RepresentationItemProvider(this);
		}

		return representationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.WildCard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WildCardItemProvider wildCardItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.WildCard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWildCardAdapter() {
		if (wildCardItemProvider == null) {
			wildCardItemProvider = new WildCardItemProvider(this);
		}

		return wildCardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.Armani} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArmaniItemProvider armaniItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.Armani}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArmaniAdapter() {
		if (armaniItemProvider == null) {
			armaniItemProvider = new ArmaniItemProvider(this);
		}

		return armaniItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.BindableElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BindableElementItemProvider bindableElementItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.BindableElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBindableElementAdapter() {
		if (bindableElementItemProvider == null) {
			bindableElementItemProvider = new BindableElementItemProvider(this);
		}

		return bindableElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link aspectualacme.TypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeDefinitionItemProvider typeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link aspectualacme.TypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeDefinitionAdapter() {
		if (typeDefinitionItemProvider == null) {
			typeDefinitionItemProvider = new TypeDefinitionItemProvider(this);
		}

		return typeDefinitionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (rootItemProvider != null) rootItemProvider.dispose();
		if (importItemProvider != null) importItemProvider.dispose();
		if (elementItemProvider != null) elementItemProvider.dispose();
		if (familyItemProvider != null) familyItemProvider.dispose();
		if (componentTypeItemProvider != null) componentTypeItemProvider.dispose();
		if (roleTypeItemProvider != null) roleTypeItemProvider.dispose();
		if (portTypeItemProvider != null) portTypeItemProvider.dispose();
		if (connectorTypeItemProvider != null) connectorTypeItemProvider.dispose();
		if (propertyTypeItemProvider != null) propertyTypeItemProvider.dispose();
		if (systemItemProvider != null) systemItemProvider.dispose();
		if (componentItemProvider != null) componentItemProvider.dispose();
		if (connectorItemProvider != null) connectorItemProvider.dispose();
		if (roleItemProvider != null) roleItemProvider.dispose();
		if (baseRoleItemProvider != null) baseRoleItemProvider.dispose();
		if (crosscuttingRoleItemProvider != null) crosscuttingRoleItemProvider.dispose();
		if (portItemProvider != null) portItemProvider.dispose();
		if (propertyItemProvider != null) propertyItemProvider.dispose();
		if (glueItemProvider != null) glueItemProvider.dispose();
		if (attachmentItemProvider != null) attachmentItemProvider.dispose();
		if (bindingItemProvider != null) bindingItemProvider.dispose();
		if (representationItemProvider != null) representationItemProvider.dispose();
		if (wildCardItemProvider != null) wildCardItemProvider.dispose();
		if (bindableElementItemProvider != null) bindableElementItemProvider.dispose();
		if (typeDefinitionItemProvider != null) typeDefinitionItemProvider.dispose();
		if (armaniItemProvider != null) armaniItemProvider.dispose();
		if (armaniExpressionItemProvider != null) armaniExpressionItemProvider.dispose();
		if (armaniFunctionCallItemProvider != null) armaniFunctionCallItemProvider.dispose();
		if (armaniSetExpressionItemProvider != null) armaniSetExpressionItemProvider.dispose();
		if (armaniConstantItemProvider != null) armaniConstantItemProvider.dispose();
		if (armaniPrimitiveExpressionItemProvider != null) armaniPrimitiveExpressionItemProvider.dispose();
		if (armaniUnaryExpressionItemProvider != null) armaniUnaryExpressionItemProvider.dispose();
		if (armaniMultiplicativeExpressionItemProvider != null) armaniMultiplicativeExpressionItemProvider.dispose();
		if (armaniAdditiveExpressionItemProvider != null) armaniAdditiveExpressionItemProvider.dispose();
		if (armaniRelationalExpressionItemProvider != null) armaniRelationalExpressionItemProvider.dispose();
		if (armaniEqualityExpressionItemProvider != null) armaniEqualityExpressionItemProvider.dispose();
		if (armaniIffExpressionItemProvider != null) armaniIffExpressionItemProvider.dispose();
		if (armaniImpliesExpressionItemProvider != null) armaniImpliesExpressionItemProvider.dispose();
		if (armaniOrExpressionItemProvider != null) armaniOrExpressionItemProvider.dispose();
		if (armaniVariableItemProvider != null) armaniVariableItemProvider.dispose();
		if (armaniBooleanExpressionItemProvider != null) armaniBooleanExpressionItemProvider.dispose();
		if (armaniQuantifiedExpressionItemProvider != null) armaniQuantifiedExpressionItemProvider.dispose();
	}

}
