/*
* generated by Xtext
*/
package dimap.ufrn.br.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AspectualAcmeProposalProvider extends AbstractAspectualAcmeProposalProvider {

}
