/*
 * generated by Xtext
 */
package dimap.ufrn.br.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AspectualAcmeUiModule extends dimap.ufrn.br.ui.AbstractAspectualAcmeUiModule {
	public AspectualAcmeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
