/*
* generated by Xtext
*/
package dimap.ufrn.br.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class AspectualAcmeTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
